overmindtech/aws-source

- .github/workflows/test-build.yml
- README.md
- cmd/root.go
- sources/ec2/main_test.go
- sources/elasticloadbalancing/main_test.go
- sources/securitygroup/main_test.go
- sources/shared_tests.go
* create sources per region
Also:
* redact secret key from log
* fix docs
* typos
> Add multi-region support

- cmd/root.go
- go.mod
- go.sum
- sources/always_get_source.go
- sources/always_get_source_test.go
- sources/describe_source.go
- sources/eks/addon.go
- sources/eks/cluster.go
- sources/eks/fargate_profile.go
- sources/eks/node_group.go
- sources/get_list_source.go
- sources/get_list_source_test.go
- sources/route53/hosted_zone.go
- sources/route53/hosted_zone_test.go
- sources/route53/resource_record_set.go
- sources/route53/resource_record_set_test.go
- sources/sources.go
This adds some basic route 53 info
> Create route 53 source

- cmd/root.go
- go.mod
- go.sum
- sources/iam/group.go
- sources/iam/group_test.go
- sources/iam/policy.go
- sources/iam/policy_test.go
- sources/iam/role.go
- sources/iam/role_test.go
- sources/iam/shared.go
- sources/iam/shared_test.go
- sources/iam/user.go
- sources/iam/user_test.go
> Create IAM source

- README.md
- cmd/root.go
- go.mod
- go.sum
- sources/always_get_source.go
- sources/get_list_source.go
- sources/lambda/function.go
- sources/lambda/function_test.go
- sources/lambda/layer.go
- sources/lambda/layer_test.go
- sources/lambda/layer_version.go
- sources/lambda/layer_version_test.go
- sources/lambda/shared.go
- sources/lambda/shared_test.go
- sources/util.go
> Create lambda source

- cmd/root.go
See https://flowerinthenight.com/blog/2021/04/30/authenticate-aws-sdk-golang-v2
> Implement AssumeRole credential source

- cmd/root.go
> Added termination log hook

- sources/autoscaling/auto_scaling_group.go
- sources/autoscaling/auto_scaling_group_test.go
- sources/dynamodb/table.go
- sources/dynamodb/table_test.go
- sources/ec2/instance_status.go
- sources/ec2/instance_status_test.go
- sources/ec2/instance_test.go
- sources/ec2/volume.go
- sources/ec2/volume_test.go
- sources/ecs/task.go
- sources/ecs/task_test.go
- sources/elbv2/target_health.go
- sources/elbv2/target_health_test.go
- sources/rds/db_cluster.go
- sources/rds/db_cluster_test.go
- sources/rds/db_instance_test.go
I wasn't sure about this at first but I think it's actually useful data, plus now that we have hiding it's not so bad
> Added AZ links to more things

- go.mod
- go.sum
- sources/iam/role.go
- sources/iam/role_test.go
- sources/iam/shared.go
> 183-iam-role-search-doesnt-find-any-policies

- sources/always_get_source.go
- sources/always_get_source_test.go
- sources/eks/fargate_profile.go
- sources/eks/node_group.go
These sources didn't previously support this, making their terraform mapping wrong
> Add ARN search support

- sources/get_list_source.go
- sources/iam/policy.go
- sources/iam/policy_test.go
> Fixed "aws" sources polluting other scopes

- cmd/root.go
- go.mod
- go.sum
- sources/iam/policy.go
- sources/iam/policy_test.go
- sources/iam/role.go
- sources/iam/shared_test.go
- sources/iam/tracing.go
- sources/limit_bucket.go
- sources/util.go
- tracing/tracing.go
- tracing/tracing_test.go
We really need to know what the cause of this is before we start hitting large environments as it'll take way too long at the current rate. I'm pretty sure it's rate limiting but we'll have to see
> Added tracing to be sure why IAM takes so long

- go.mod
Reverts overmindtech/aws-source#279
> Revert "Update Observability modules"

- cmd/root.go
- docs-data/directconnect-virtual-gateway.json
- sources/describe_source.go
- sources/describe_source_test.go
- sources/directconnect/direct-connect-gateway-association.go
- sources/directconnect/direct-connect-gateway.go
- sources/directconnect/virtual-gateway.go
- sources/directconnect/virtual-gateway_test.go
> Add direct connect virtual gateway source

- cmd/root.go
- docs-data/directconnect-customer-metadata.json
- docs-data/directconnect-hosted-connection.json
- docs-data/directconnect-interconnect.json
- docs-data/directconnect-lag.json
- docs-data/directconnect-location.json
- docs-data/directconnect-router-configuration.json
- sources/directconnect/connection.go
- sources/directconnect/customer-metadata.go
- sources/directconnect/customer-metadata_test.go
- sources/directconnect/direct-connect-gateway.go
- sources/directconnect/direct-connect-gateway_test.go
- sources/directconnect/hosted-connection.go
- sources/directconnect/hosted-connection_test.go
- sources/directconnect/interconnect.go
- sources/directconnect/interconnect_test.go
- sources/directconnect/lag.go
- sources/directconnect/lag_test.go
- sources/directconnect/location.go
- sources/directconnect/location_test.go
- sources/directconnect/router-configuration.go
- sources/directconnect/router-configuration_test.go
- sources/directconnect/shared.go
Add following direct connect sources:
- Location
- Lag
- Customer Metadata
- LOA
- Hosted Connection
- Interconnect
- Router Configuration
Resolves #326
> Add more direct connect sources

- cmd/root.go
This is a quick refactor to make configuring the AWS Source from code easier.
> Refactor to ease configuration in code

- README.md
- cmd/root.go
- docs-data/sns-subscription.json
- docs-data/sns-topic.json
- go.mod
- go.sum
- sources/sns/shared.go
- sources/sns/subscription.go
- sources/sns/subscription_test.go
- sources/sns/topic.go
- sources/sns/topic_test.go
- sources/sqs/queue_test.go
> Add sns topic and subscription sources

- README.md
- cmd/root.go
- docs-data/sns-endpoint.json
- docs-data/sns-platform-application.json
- sources/sns/endpoint.go
- sources/sns/endpoint_test.go
- sources/sns/platform-application.go
- sources/sns/platform-application_test.go
- sources/sns/shared.go
- sources/sns/subscription.go
- sources/sns/topic.go
> Add sns endpoint and platform-application sources

- sources/elbv2/target_health.go
This prevents overflows, fixes #419 and closes the associated security issue
> Added size check to integer conversion

- proc/proc.go
- sources/iam/group.go
- sources/iam/group_test.go
- sources/iam/instance_profile.go
- sources/iam/instance_profile_test.go
- sources/iam/policy.go
- sources/iam/policy_test.go
- sources/iam/role.go
- sources/iam/role_test.go
- sources/iam/user.go
- sources/iam/user_test.go
No idea how I missed this in the last refactor, this is pretty much the most important source to have a shared client too
> Move IAM to a shared client

- sources/dynamodb/table.go
> Add empty string check to dynamo source

- sources/case.go
- sources/cloudfront/cache_policy.go
- sources/cloudfront/continuous_deployment_policy.go
- sources/cloudfront/function.go
- sources/cloudfront/key_group.go
- sources/cloudfront/origin_access_control.go
- sources/cloudfront/origin_request_policy.go
- sources/cloudfront/realtime_log_configs.go
- sources/cloudfront/response_headers_policy.go
- sources/describe_source.go
- sources/directconnect/direct-connect-gateway.go
- sources/dynamodb/table.go
- sources/eks/addon.go
- sources/eks/cluster.go
- sources/eks/fargate_profile.go
- sources/eks/node_group.go
- sources/iam/group.go
- sources/iam/instance_profile.go
- sources/iam/user.go
- sources/lambda/function.go
- sources/networkmanager/core_network.go
- sources/route53/health_check.go
- sources/route53/hosted_zone.go
- sources/route53/resource_record_set.go
> Fix dynamo derp

- proc/proc.go
> Initialize sources in parallel to remove ~13s startup time from the CLI

- sources/iam/policy.go
- sources/iam/role.go
- sources/iam/role_test.go
- sources/iam/shared.go
This also extracts links from them using the same logic as for policies
> Added parsing for embedded policy documents in roles

- .github/workflows/test-build.yml
- docs-data/ec2-security-group-rule.json
- docs-data/elbv2-load-balancer.json
- docs-data/route53-resource-record-set.json
- sources/ec2/sg_rule.go
- sources/elbv2/elb.go
- sources/lambda/function.go
- sources/lambda/policy_parser_test.go
- sources/route53/health_check.go
- sources/route53/resource_record_set.go
- sources/route53/resource_record_set_test.go
> Fix mapping issues

- README.md
- docs-data/kms-alias.json
- proc/proc.go
- sources/integration/kms/create.go
- sources/integration/kms/delete.go
- sources/integration/kms/find.go
- sources/integration/kms/kms_test.go
- sources/integration/kms/setup.go
- sources/integration/kms/teardown.go
- sources/kms/alias.go
- sources/kms/alias_test.go
- sources/kms/custom-key-store_test.go
Add KMS Alias source
Related to: https://github.com/overmindtech/aws-source/issues/393
> add kms alias source

- sources/always_get_source.go
- sources/util.go
You don't need to validate the list functions if they aren't used
> Fixed logic around validating Search queries

- proc/proc.go
- sources/util.go
https://github.com/overmindtech/cli/issues/591
> (fix) allow all configs to run in InitializeAwsSourceEngine

- adapters/route53-resource-record-set.go
- adapters/route53-resource-record-set_test.go
> Fixed record mapping for `aws_route53_record` resources
